variables:
  buildConfiguration: 'Release'
  system.debug: true

jobs:
- job: 'netcore_linux'
  container: microsoft/dotnet:latest
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '-f netcoreapp2.1 -c Release /m:1 --no-incremental'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Test/*.csproj'
      arguments: '-f netcoreapp2.1 -c Release --no-build --no-restore'

- job: 'netcore_net471_win'
  pool: 
    vmImage: vs2017-win2016
  steps:
  - script:
      dotnet build --configuration $(buildConfiguration)
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Test/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

 